version: '2.1'

services:
  study-docker:
    image: study-docker
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
      - 9229:9229
    command: node --inspect index.js